create table USERS
(
    ID       bigint generated by default as identity,
    LOGIN    varchar(100) not null,
    PASSWORD varchar(100) not null,
    primary key (ID)
);

create table FILES
(
    ID           bigint generated by default as identity,
    FILE_NAME    varchar(100) not null,
    FILE_CONTENT bytea,
    FILE_SIZE    bigint,
    USER_ID      bigint,
    primary key (ID)
);

create table AUTH_TOKENS
(
    TOKEN   varchar(250),
    USER_ID bigint,
    primary key (TOKEN)
);

alter table if exists FILES
    add constraint FK_FILES_USER_ID
        foreign key (USER_ID)
            references USERS;


