server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root

  sql:
    init:
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: netology

  servlet:
    multipart:
      enabled: true
      max-file-size: 60MB
      max-request-size: 60MB
